spring.application.name=tournament
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/archery_tournament
server.port=8083
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
jwt.secret=RQoKhXY5ueqOk8Pe24sLfkKYFbXQJ0uQYp7e40z0abcdef123456789
logging.level.org.springframework.security=DEBUG
