spring.application.name=team-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/archery_team
spring.datasource.username=postgres
spring.datasource.password=1234
server.port=8082
spring.jpa.hibernate.ddl-auto=update
jwt.secret=RQoKhXY5ueqOk8Pe24sLfkKYFbXQJ0uQYp7e40z0abcdef123456789